### ISSUE TITLE
Error while launching QGIS

### ISSUE THREAD

**Issue by Gustry** [NathanW2/qgiscommand#26]
Each time I start QGIS, I have this error : 

```
Traceback (most recent call last):
  File "/home/etienne/.qgis2/python/plugins/qgiscommand/__init__.py", line 55, in load_init_file
    command.load_from_file(initfile)
  File "/home/etienne/.qgis2/python/plugins/qgiscommand/command.py", line 306, in load_from_file
    funcname, func, data = parse_line(match)
TypeError: 'NoneType' object is not iterable
```

QGIS 2.8.1 & master, kubuntu

**Comment by NathanW2** [comment]
Thanks.  I will have a look into it.

**Comment by Gustry** [comment]
It's with the last version of the plugin.
Before, maybe two versions ago, it was fine.

**Comment by NathanW2** [comment]
Should be fixed now
